<a href="https://colab.research.google.com/github/snatabag/Samsung-Assignment/blob/main/homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [131]:
import numpy as np


In [132]:

# 1. Create a 5×5 matrix with values 1–25
a1 = np.arange(1, 26).reshape(5, 5)
print("1:\n", a1)

1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [133]:
# 2. Generate a 4×4 identity matrix
a2 = np.eye(4)
print("\n2:\n", a2)


2:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [134]:
# 3. 1D array of numbers from 100 to 200 with step 10
a3 = np.arange(100, 201, 10)
print("\n3:\n", a3)


3:
 [100 110 120 130 140 150 160 170 180 190 200]


In [135]:
# 4. Random 3×3 matrix and determinant
a4 = np.random.rand(3, 3)
print("\n4:\n", a4, "\nDet:", np.linalg.det(a4))



4:
 [[0.97956605 0.76744694 0.6895864 ]
 [0.74353914 0.66514134 0.51872468]
 [0.69597078 0.96443751 0.6893293 ]] 
Det: 0.01806704938708176


In [136]:
# 5. Array of 10 random integers between 1 and 100
a5 = np.random.randint(1, 101, 10)
print("\n5:\n", a5)


5:
 [16 16 66 49 97 78 75 21 45 45]


In [137]:
# 6. Reshape 1D array of size 12 to 3×4
a6 = np.arange(12).reshape(3, 4)
print("\n6:\n", a6)


6:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [97]:
# 7. Matrix multiplication of two 3×3 matrices
m1, m2 = np.random.randint(1, 10, (3, 3)), np.random.randint(1, 10, (3, 3))
print("\n7:\n", m1 @ m2)


7:
 [[ 26 118  94]
 [ 26  81  96]
 [ 54 126 110]]


In [98]:
# 8. Eigenvalues and eigenvectors of 2×2 matrix
m = np.array([[2, 1], [1, 2]])
w, v = np.linalg.eig(m)
print("\n8:\nEigenvalues:", w, "\nEigenvectors:\n", v)


8:
Eigenvalues: [3. 1.] 
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [99]:
# 9. 5×5 random matrix and diagonal
a9 = np.random.rand(5, 5)
print("\n9:\n", np.diag(a9))


9:
 [0.38829511 0.76674289 0.57279315 0.60052569 0.63047062]


In [100]:
# 10. Normalize 1D array
arr4 = np.random.randint(1, 20, 10)
norm_arr = (arr4 - arr4.min()) / (arr4.max() - arr4.min())
print(norm_arr)

[0.1875 0.625  0.6875 0.3125 0.3125 0.6875 1.     0.5    0.     0.75  ]


In [101]:
# 11. Sort array by row and column
a11 = np.random.randint(1, 50, (3, 3))
print("\n11 Original:\n", a11)
print("Row-wise:\n", np.sort(a11, axis=1))
print("Column-wise:\n", np.sort(a11, axis=0))


11 Original:
 [[39 45 34]
 [11 12 37]
 [42 39 13]]
Row-wise:
 [[34 39 45]
 [11 12 37]
 [13 39 42]]
Column-wise:
 [[11 12 13]
 [39 39 34]
 [42 45 37]]


In [102]:
# 12. Indices of max and min
a12 = np.random.randint(1, 100, 10)
print("\n12:\n", a12, "\nMax idx:", a12.argmax(), "Min idx:", a12.argmin())



12:
 [ 6 46 86 19 27 85 83  5 67 41] 
Max idx: 2 Min idx: 7


In [103]:
# 13. Flatten array
a13 = np.arange(9).reshape(3, 3)
print("\n13 ravel:", a13.ravel(), "flatten:", a13.flatten())



13 ravel: [0 1 2 3 4 5 6 7 8] flatten: [0 1 2 3 4 5 6 7 8]


In [104]:
# 14. Inverse of 3×3 matrix
a14 = np.random.randint(1, 10, (3, 3))
print("\n14 Inverse:\n", np.linalg.inv(a14))


14 Inverse:
 [[ 0.34177215 -0.13924051 -0.03797468]
 [-0.39240506 -0.02531646  0.26582278]
 [ 0.13924051  0.20253165 -0.12658228]]


In [105]:
# 15. Random permutation of 1–10
print("\n15:\n", np.random.permutation(np.arange(1, 11)))




15:
 [ 4  5  6 10  7  2  9  1  3  8]


In [106]:
# 16. Replace even numbers with -1
a16 = np.arange(21)
a16[a16 % 2 == 0] = -1
print("\n16:\n", a16)


16:
 [-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [107]:

# 17. Dot product of two arrays
a17 = np.array([1, 2, 3]); b17 = np.array([4, 5, 6])
print ("\n17:\n", np.dot(a17, b17))


17:
 32


In [108]:

# 18. Trace of random 5×5
a18 = np.random.rand(5, 5)
print("\n18 Trace:", np.trace(a18))


18 Trace: 1.8388003763388299


In [109]:

# 19. Split 1D array into 3 equal parts
a19 = np.arange(12)
print("\n19:\n", np.split(a19, 3))



19:
 [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [110]:
# 20. 3D array mean across axis=0
a20 = np.random.rand(3, 3, 3)
print("\n20:\n", a20.mean(axis=0))


20:
 [[0.61409251 0.37145222 0.47020997]
 [0.31847699 0.42281591 0.36196803]
 [0.27407508 0.44249032 0.54623601]]


In [111]:
# 21. Cumulative sum
a21 = np.arange(1, 6)
print("\n21:\n", np.cumsum(a21))


21:
 [ 1  3  6 10 15]


In [112]:
# 22. Upper triangular matrix
a22 = np.random.randint(1, 10, (4, 4))
print("\n22:\n", np.triu(a22))


22:
 [[2 5 6 6]
 [0 2 4 4]
 [0 0 7 7]
 [0 0 0 5]]


In [113]:
# 23. 6×6 checkerboard
a23 = np.indices((6, 6)).sum(axis=0) % 2
print("\n23:\n", a23)


23:
 [[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [114]:
# 24. Element-wise sqrt
a24 = np.random.rand(3, 3)
print("\n24:\n", np.sqrt(a24))


24:
 [[0.67256227 0.65253525 0.40885344]
 [0.69935014 0.87652759 0.45206294]
 [0.16665896 0.9570202  0.81713613]]


In [115]:
# 25. Reverse array (no slicing)
a25 = np.arange(20)
print("\n25:\n", np.flip(a25))


25:
 [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [116]:
# 26. Merge arrays vertically & horizontally
a26, b26 = np.ones((2, 2)), np.zeros((2, 2))
print("\n26 vstack:\n", np.vstack((a26, b26)), "\nhstack:\n", np.hstack((a26, b26)))


26 vstack:
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]] 
hstack:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]


In [117]:
# 27. Row-wise and column-wise sum
a27 = np.random.randint(1, 10, (3, 3))
print("\n27 Row sum:", a27.sum(axis=1), "Col sum:", a27.sum(axis=0))


27 Row sum: [14 14 16] Col sum: [13 17 14]


In [118]:
# 28. Replace NaN with column mean
a28 = np.array([[1, np.nan, 3], [4, 5, np.nan]])
col_mean = np.nanmean(a28, axis=0)
inds = np.where(np.isnan(a28))
a28[inds] = np.take(col_mean, inds[1])
print("\n28:\n", a28)


28:
 [[1. 5. 3.]
 [4. 5. 3.]]


In [119]:
# 29. Cosine similarity
a29, b29 = np.array([1, 2, 3]), np.array([4, 5, 6])
cos_sim = np.dot(a29, b29) / (np.linalg.norm(a29) * np.linalg.norm(b29))
print("\n29 Cosine similarity:", cos_sim)


29 Cosine similarity: 0.9746318461970762


In [120]:
# 30. Rotate 4×4 by 90°
a30 = np.arange(16).reshape(4, 4)
print("\n30:\n", np.rot90(a30))


30:
 [[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]


In [121]:
# 31. Structured array
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('marks', 'f4')])
a31 = np.array([('Alex', 21, 88.5), ('Bob', 22, 91.0)], dtype=dt)
print("\n31:\n", a31)


31:
 [('Alex', 21, 88.5) ('Bob', 22, 91. )]


In [122]:
# 32. Rank of 3×3 matrix
a32 = np.random.randint(1, 10, (3, 3))
print("\n32 Rank:", np.linalg.matrix_rank(a32))


32 Rank: 3


In [123]:
# 33. Normalize each row to unit length
a33 = np.random.rand(5, 5)
a33 = a33 / np.linalg.norm(a33, axis=1, keepdims=True)
print("\n33:\n", a33)


33:
 [[0.09534602 0.46149525 0.52364424 0.08194963 0.70499095]
 [0.29103215 0.61646806 0.55936768 0.20188147 0.4261679 ]
 [0.31904708 0.84492992 0.16263986 0.39426324 0.04906292]
 [0.69798771 0.5726108  0.01622312 0.30346682 0.30426097]
 [0.69623821 0.33485251 0.52603697 0.30379262 0.18471952]]


In [124]:
# 34. Check element-wise equality
print("\n34:", np.array_equal([1, 2], [1, 2]))


34: True


In [125]:
# 35. Histogram of 1000 numbers
a35 = np.random.randn(1000)
hist, bins = np.histogram(a35, bins=10)
print("\n35 Histogram:\n", hist)


35 Histogram:
 [  4  15  53 149 211 228 209  84  36  11]


In [126]:
# 36. Broadcasting add
a36 = np.array([[1], [2], [3]])
b36 = np.array([4, 5, 6])
print("\n36:\n", a36 + b36)


36:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [127]:
# 37. Unique values and counts
a37 = np.array([1, 2, 2, 3, 3, 3])
vals, counts = np.unique(a37, return_counts=True)
print("\n37:\n", dict(zip(vals, counts)))


37:
 {np.int64(1): np.int64(1), np.int64(2): np.int64(2), np.int64(3): np.int64(3)}


In [128]:
# 38. Pearson correlation coefficient
a38, b38 = np.array([1, 2, 3]), np.array([4, 5, 6])
print("\n38 Corrcoef:\n", np.corrcoef(a38, b38))


38 Corrcoef:
 [[1. 1.]
 [1. 1.]]


In [129]:
# 39. Numerical gradient
a39 = np.array([1, 2, 4, 7, 11])
print("\n39 Gradient:", np.gradient(a39))


39 Gradient: [1.  1.5 2.5 3.5 4. ]


In [130]:
# 40. SVD of random 3×3
a40 = np.random.rand(3, 3)
U, S, V = np.linalg.svd(a40)
print("\n40:\nU:\n", U, "\nS:\n", S, "\nV:\n", V)


40:
U:
 [[-0.87740285 -0.19193349 -0.43968828]
 [-0.31181076 -0.46837675  0.82667846]
 [-0.36460704  0.86242957  0.35110816]] 
S:
 [1.47475148 0.53985631 0.05256082] 
V:
 [[-0.72416784 -0.1406238  -0.67513398]
 [ 0.58577572  0.39120871 -0.70980459]
 [-0.36393371  0.90949474  0.20092676]]
